[package]
name = "server"
version = "1.3.0"
edition = "2024"

[dependencies]
shared.workspace = true
utils.workspace = true

postcard.workspace = true
serde_json.workspace = true
uuid.workspace = true

axum = {
    version = "0.8",
    default-features = false,
    features = ["http1", "json", "ws"],
}
tokio = { version = "1.53", default-features = false, features = [
    "io-util",
    "macros",
    "net",
    "rt-multi-thread",
    "time",
] }
