macro_rules! model {
    ($name:literal) => {
        model!($name, $name)
    };
    ($name:literal, $file:literal) => {
        ModelInfo {
            data: include_bytes!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/assets/models/",
                $file,
                ".glb"
            )),
            name: $name,
        }
    };
}

#[derive(Clone, Copy)]
pub struct ModelInfo {
    pub data: &'static [u8],
    pub name: &'static str,
}

#[cfg(feature = "reduced-models")]
pub static MODELS: &[ModelInfo] = &[
    model!("ctm_diver", "ctm_diver_varianta"),
    model!("ctm_fbi"),
    model!("ctm_gendarmerie", "ctm_gendarmerie_varianta"),
    model!("ctm_sas"),
    model!("ctm_st6", "ctm_st6_variante"),
    model!("ctm_swat", "ctm_swat_variante"),
    model!("tm_balkan", "tm_balkan_variantf"),
    model!("tm_jungle_raider", "tm_jungle_raider_varianta"),
    model!("tm_leet", "tm_leet_varianta"),
    model!("tm_phoenix"),
    model!("tm_professional", "tm_professional_varf"),
];

#[cfg(not(feature = "reduced-models"))]
pub static MODELS: &[ModelInfo] = &[
    model!("ctm_diver_varianta"),
    model!("ctm_diver_variantb"),
    model!("ctm_diver_variantc"),
    model!("ctm_fbi"),
    model!("ctm_fbi_varianta"),
    model!("ctm_fbi_variantb"),
    model!("ctm_fbi_variantc"),
    model!("ctm_fbi_variantd"),
    model!("ctm_fbi_variante"),
    model!("ctm_fbi_variantf"),
    model!("ctm_fbi_variantg"),
    model!("ctm_fbi_varianth"),
    model!("ctm_gendarmerie_varianta"),
    model!("ctm_gendarmerie_variantb"),
    model!("ctm_gendarmerie_variantc"),
    model!("ctm_gendarmerie_variantd"),
    model!("ctm_gendarmerie_variante"),
    model!("ctm_sas"),
    model!("ctm_sas_variantf"),
    model!("ctm_sas_variantg"),
    model!("ctm_st6_variante"),
    model!("ctm_st6_variantg"),
    model!("ctm_st6_varianti"),
    model!("ctm_st6_variantj"),
    model!("ctm_st6_variantk"),
    model!("ctm_st6_variantl"),
    model!("ctm_st6_variantm"),
    model!("ctm_st6_variantn"),
    model!("ctm_swat_variante"),
    model!("ctm_swat_variantf"),
    model!("ctm_swat_variantg"),
    model!("ctm_swat_varianth"),
    model!("ctm_swat_varianti"),
    model!("ctm_swat_variantj"),
    model!("ctm_swat_variantk"),
    model!("tm_balkan_variantf"),
    model!("tm_balkan_variantg"),
    model!("tm_balkan_varianth"),
    model!("tm_balkan_varianti"),
    model!("tm_balkan_variantj"),
    model!("tm_balkan_variantk"),
    model!("tm_balkan_variantl"),
    model!("tm_jungle_raider_varianta"),
    model!("tm_jungle_raider_variantb"),
    model!("tm_jungle_raider_variantb2"),
    model!("tm_jungle_raider_variantc"),
    model!("tm_jungle_raider_variantd"),
    model!("tm_jungle_raider_variante"),
    model!("tm_jungle_raider_variantf"),
    model!("tm_jungle_raider_variantf2"),
    model!("tm_leet_varianta"),
    model!("tm_leet_variantb"),
    model!("tm_leet_variantc"),
    model!("tm_leet_variantd"),
    model!("tm_leet_variante"),
    model!("tm_leet_variantf"),
    model!("tm_leet_variantg"),
    model!("tm_leet_varianth"),
    model!("tm_leet_varianti"),
    model!("tm_leet_variantj"),
    model!("tm_leet_variantk"),
    model!("tm_phoenix"),
    model!("tm_phoenix_varianta"),
    model!("tm_phoenix_variantb"),
    model!("tm_phoenix_variantc"),
    model!("tm_phoenix_variantd"),
    model!("tm_phoenix_variantf"),
    model!("tm_phoenix_variantg"),
    model!("tm_phoenix_varianth"),
    model!("tm_phoenix_varianti"),
    model!("tm_professional_varf"),
    model!("tm_professional_varf1"),
    model!("tm_professional_varf2"),
    model!("tm_professional_varf3"),
    model!("tm_professional_varf4"),
    model!("tm_professional_varf5"),
    model!("tm_professional_varg"),
    model!("tm_professional_varh"),
    model!("tm_professional_vari"),
    model!("tm_professional_varj"),
];
